### REGISTER USER
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "mrlcetus1",
    "password": "password"
}

### LOGIN USER
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "mrlcetus",
    "password": "password"
}

